Feature/my results integration
peaksoft-school/bilingual-js10 pull request #90
Opened 2023-11-30 14:59 UTC by Nurlan-Abdullaev

2023-12-01 10:21 UTC, AziatAbd requested changes

2023-12-01 10:21 UTC, AziatAbd commented on src/components/clientTest/user-result/UserResult.jsx
> +   }
![image](https://github.com/peaksoft-school/bilingual-js10/assets/115453436/f1329435-88a0-4dae-8f04-b46ac9516cff)
не ошибка бул?

2023-12-01 10:21 UTC, AziatAbd commented on src/components/clientTest/user-result/UserResult.jsx
> +         await axiosInstanceS3File.delete(`/result/?userId=1&testId=1`)
неге тест id статичный

2023-12-01 10:21 UTC, AziatAbd commented on src/components/clientTest/user-result/UserResult.jsx
> +         console.error(error)
console убираем

2023-12-01 10:21 UTC, AziatAbd commented on src/components/clientTest/user-result/UserResult.jsx
> +         const response = await axiosInstanceS3File.get(
обычный axiosInstance колдонсо болбойбу?

2023-12-01 10:21 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/bilingual-js10/assets/115453436/365e113c-eadb-435f-8b95-1210a0999fd0)
скролл убираем

2023-12-01 10:22 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/bilingual-js10/assets/115453436/8e6f59dd-91ac-4e49-bff9-b4ee424a244d)
роут кошкула

2023-12-01 10:22 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/bilingual-js10/assets/115453436/efa753b2-d090-4899-8d81-40017f23e02e)
figma менен ушуну салыштырып корун дагы ондон

2023-12-02 06:24 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/bilingual-js10/assets/115453436/25264dab-3cd9-442b-8544-c6325cda0ea0)
удаление иштебейт

2023-12-02 06:25 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/bilingual-js10/assets/115453436/67e2bf73-4d6e-4d49-9a18-2091943c0e71)

![image](https://github.com/peaksoft-school/bilingual-js10/assets/115453436/144f9c6f-f147-4b73-8556-16aab281b557)

неге сиздики true, false деп турат

2023-12-02 06:26 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/bilingual-js10/assets/115453436/62cd2eda-6678-450a-8df0-519a34f079ba)
![image](https://github.com/peaksoft-school/bilingual-js10/assets/115453436/54458372-88df-4a3e-a35e-2587897e5f4e)

figma'дагыдай кылып ондон header'ди. My result'та турса кок болуп туруш керек

2023-12-02 06:27 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/bilingual-js10/assets/115453436/8ff3b5c3-9e22-4601-ac28-a44ab613a1d2)
скролл жок кылгыла

2023-12-02 06:29 UTC, AziatAbd requested changes

2023-12-02 06:29 UTC, AziatAbd commented on src/components/clientTest/user-result/UserResult.jsx
> +   }
getData деп коюн

2023-12-02 06:44 UTC, Nurlan-Abdullaev commented
удаление swagger иштебей жатат

2023-12-02 10:15 UTC, AziatAbd requested changes

2023-12-02 10:15 UTC, AziatAbd commented on src/components/clientTest/user-result/UserResult.jsx
>           await axiosInstance.delete(`/result/?userId=12&testId=${userTestID}`)
неге userId статичный? если менин id 15 болсо то мен башка бироонун эле ресалтын удалить этип таштайм

2023-12-03 08:09 UTC, merged